"""Accessibility Agent — enriches messages with multimodal accessibility metadata."""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, ClassVar, List, Optional, cast

from agents.base_agent import BaseAgent
from mcp.mcp_client import MCPClient, mcp_client as _default_mcp_client
from shared.message_schema import (
    AccessibilityFeature,
    AccessibleMessage,
    AvatarReadyMessage,
    MessageType,
    RoutedMessage,
)

if TYPE_CHECKING:
    from agents.agent_bus import AsyncAgentBus
    from shared.message_schema import BaseMessage

logger = logging.getLogger(__name__)


class AccessibilityAgent(BaseAgent):
    """Enriches messages with multimodal accessibility features."""

    # Agent Mesh: consume ROUTED events from the bus
    subscribes_to: ClassVar[List[MessageType]] = [MessageType.ROUTED]

    def __init__(self, mcp_client: Optional[MCPClient] = None) -> None:
        self._mcp_client = mcp_client or _default_mcp_client

    async def process(self, msg: RoutedMessage) -> AccessibleMessage:
        features = [AccessibilityFeature.SUBTITLES]
        metadata = dict(msg.metadata)

        logger.info("AccessibilityAgent.process — session=%s text=%s", msg.session_id, msg.text[:80])

        # Only TTS audio — gloss sequence is generated by AvatarAgent using the
        # sign-adapted text from TranslationAgent (higher quality, no redundant call).
        language = metadata.get("language", "en-US")
        tts_result = await self._mcp_client.call_tool(
            "text_to_speech_tool", text=msg.text, language=language
        )

        if tts_result.success and tts_result.data:
            audio_b64 = tts_result.data.get("audio_b64", "")
            if audio_b64:
                metadata["audio_b64"] = audio_b64
                metadata["audio_content_type"] = tts_result.data.get("content_type", "audio/mp3")
                features.append(AccessibilityFeature.AUDIO_DESCRIPTION)

        accessible = AccessibleMessage(
            session_id=msg.session_id,
            sender_id=msg.sender_id,
            text=msg.text,
            features_applied=features,
            aria_labels={
                "role": "log",
                "aria-live": "polite",
                "aria-label": f"Caption from {msg.sender_id}: {msg.text}",
            },
            metadata=metadata,
        )

        logger.info("AccessibilityAgent: session=%s features=%s audio=%s",
                    msg.session_id, [f.value for f in features],
                    "yes" if metadata.get("audio_b64") else "no")
        return accessible

    # ── Agent Mesh handler ────────────────────────────────────────────

    async def handle(self, event: "BaseMessage", bus: "AsyncAgentBus") -> None:
        """
        Receive a RoutedMessage, enrich with TTS audio, and publish an
        AccessibleMessage carrying ``correlation_id``.

        Short-circuit path: when ``avatar_agent`` is not in ``target_agents``
        (e.g. router classified the message as command-only), this handler
        also publishes a minimal AvatarReadyMessage so that the caller's
        ``publish_and_collect(collect_type=AVATAR_READY)`` always resolves
        and never times out.
        """
        correlation_id = event.metadata.get("correlation_id", event.message_id)
        try:
            routed = cast(RoutedMessage, event)
            accessible = await self.process(routed)
            accessible.metadata["correlation_id"] = correlation_id
            await bus.publish(accessible)

            # Short-circuit: if AvatarAgent is not part of the pipeline,
            # publish a passthrough AvatarReadyMessage so publish_and_collect resolves.
            if "avatar_agent" not in routed.target_agents:
                logger.info(
                    "AccessibilityAgent: avatar_agent not in pipeline — publishing passthrough AvatarReady corr=%s",
                    correlation_id,
                )
                features_applied = [
                    f.value if hasattr(f, "value") else f
                    for f in accessible.features_applied
                ]
                passthrough = AvatarReadyMessage(
                    session_id=accessible.session_id,
                    sender_id=accessible.sender_id,
                    animation_data={"gloss_sequence": accessible.metadata.get("gloss_sequence", [])},
                    metadata={
                        **accessible.metadata,
                        "correlation_id": correlation_id,
                        "original_text": accessible.text,
                        "features_applied": features_applied,
                    },
                )
                await bus.publish(passthrough)
        except Exception as exc:
            logger.error("AccessibilityAgent.handle error: %s", exc, exc_info=True)
